"use client";

import { use, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { CalendarDays, MapPin, ShieldCheck } from "lucide-react";

type Item = { id:number; owner_id:number; title:string; type:"LOST"|"FOUND"; status:string; description:string; city:string; province:string; approximate_location:string; dateOccurred:string; category:{name:string}; owner:{displayName:string}; images:Array<{url:string;alt?:string}> };

export default function ItemPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const router = useRouter();
  const [item, setItem] = useState<Item>(); const [mine, setMine] = useState(false); const [error, setError] = useState<string>(); const [pending, setPending] = useState(false);
  useEffect(() => { Promise.all([fetch(`/api/items.php?id=${encodeURIComponent(id)}`), fetch("/api/session.php", {credentials:"same-origin"})]).then(async ([itemResponse, sessionResponse]) => { const result = await itemResponse.json(); if (!itemResponse.ok) { setError(result.error || "Item not found."); return; } const record = result.data as Item; setItem(record); if (sessionResponse.ok) { const session = await sessionResponse.json(); setMine(Number(session.data?.id) === Number(record.owner_id)); } }).catch(() => setError("Unable to load this item.")); }, [id]);
  async function ownerAction(action:"delete"|"private"|"recover") { if (!item || (action === "delete" && !window.confirm("Delete this report? This cannot be undone from the public site."))) return; setPending(true); const response = await fetch(`/api/items.php?action=${action}`, {method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({id:item.id})}); if (!response.ok) { const result=await response.json(); setError(result.error || "Unable to update the item."); setPending(false); return; } router.push("/dashboard"); router.refresh(); }
  if (error) return <main className="container-page py-16 text-center"><h1 className="text-2xl font-bold">{error}</h1><Link href="/lost" className="btn-primary mt-6">Browse items</Link></main>;
  if (!item) return <main className="container-page py-16 text-center text-slate-600">Loading item…</main>;
  return <main className="container-page py-10"><div className="grid gap-8 lg:grid-cols-2"><section className="card overflow-hidden"><div className="aspect-square bg-slate-100">{item.images[0] ? <img src={item.images[0].url} alt={item.images[0].alt || item.title} className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center text-slate-400">No image provided</div>}</div></section><section><span className={`rounded-full px-3 py-1 text-sm font-bold ${item.type === "FOUND" ? "bg-emerald-100 text-emerald-700" : "bg-orange-100 text-orange-700"}`}>{item.type}</span>{item.status === "EXPIRED" && <span className="ml-2 rounded-full bg-slate-200 px-3 py-1 text-sm font-bold text-slate-700">PRIVATE</span>}<h1 className="mt-4 text-3xl font-bold">{item.title}</h1><p className="mt-2 text-slate-600">{item.category.name} · Reported by {item.owner.displayName}</p><div className="mt-7 space-y-4 text-sm"><p className="flex gap-3"><MapPin className="text-blue-700" />{item.approximate_location}, {item.city}, {item.province}</p><p className="flex gap-3"><CalendarDays className="text-blue-700" />{new Date(item.dateOccurred).toLocaleDateString("en-PH", {dateStyle:"long"})}</p></div><h2 className="mt-7 text-lg font-bold">Description</h2><p className="mt-2 whitespace-pre-wrap text-slate-700">{item.description}</p>{mine && <div className="mt-7 flex flex-wrap gap-3"><Link href={`/items/${item.id}/edit`} className="btn-primary">Edit report</Link>{item.status !== "EXPIRED" && <button disabled={pending} onClick={() => ownerAction("private")} className="btn-secondary">Make private</button>}<button disabled={pending} onClick={() => ownerAction("recover")} className="btn-secondary">Mark recovered</button><button disabled={pending} onClick={() => ownerAction("delete")} className="btn-secondary border-red-300 text-red-700 hover:bg-red-50">Delete report</button></div>}<p className="mt-6 flex gap-2 rounded-lg bg-amber-50 p-3 text-sm text-amber-900"><ShieldCheck size={18} />Never send money, passwords, OTPs, or your home address.</p></section></div></main>;
}
