
export const dynamic = "force-dynamic";
import Link from "next/link";
import { activeUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { ItemCard } from "@/components/item-card";
import { SuspendedNotice } from "@/components/suspended-notice";
export default async function Dashboard(){const _a=await activeUser();if(!_a.ok){return <SuspendedNotice reason={_a.reason} message={_a.message}/>;}const user=_a.user;const [items,matches,saved,unread,claims]=await Promise.all([db.item.findMany({where:{ownerId:user.id},include:{images:{take:1},category:true},orderBy:{createdAt:"desc"},take:6}),db.match.count({where:{OR:[{lostItemId:{in:(await db.item.findMany({where:{ownerId:user.id},select:{id:true}})).map(x=>x.id)}},{foundItemId:{in:(await db.item.findMany({where:{ownerId:user.id},select:{id:true}})).map(x=>x.id)}}]}}),db.savedItem.count({where:{userId:user.id}}),db.notification.count({where:{userId:user.id,readAt:null}}),db.claim.count({where:{item:{ownerId:user.id},status:{in:["PENDING","UNDER_REVIEW"]}}})]);const lost=items.filter(i=>i.type==="LOST").length,found=items.filter(i=>i.type==="FOUND").length;return <main className="container-page py-10"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-bold">Welcome back, {user.displayName}</h1><p className="mt-2 text-slate-600">Manage your reports and community activity.</p></div><div className="flex gap-2"><Link className="btn-secondary" href="/report/found">Report found</Link><Link className="btn-primary" href="/report/lost">Report lost</Link></div></div><div className="mt-8 grid grid-cols-2 gap-4 lg:grid-cols-4">{[["Lost reports",lost],["Found reports",found],["Possible matches",matches],["Unread notifications",unread]].map(([k,v])=><div className="card p-5" key={String(k)}><p className="text-sm text-slate-600">{k}</p><p className="mt-2 text-3xl font-bold">{v}</p></div>)}</div><div className="mt-10 flex gap-5 text-sm font-semibold text-blue-700"><Link href="/dashboard/matches">Possible matches</Link><Link href="/dashboard/claims">Claims to review ({claims})</Link><Link href="/messages">Messages</Link><Link href="/dashboard/notifications">Notifications ({unread})</Link><Link href="/dashboard/saved">Saved items ({saved})</Link></div><h2 className="mt-8 text-xl font-bold">My reports</h2>{items.length?<div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{items.map(item=><ItemCard key={item.id} item={item}/>)}</div>:<div className="card mt-5 p-10 text-center"><p>You haven&apos;t reported anything yet.</p><Link className="btn-primary mt-4" href="/report/lost">Report lost item</Link></div>}</main>}

